-- UN PROCEDIMIENTO ALMACENADO QUE RECIBE LA CLAVE DE UN EMPLEADO, REGRESA EL LISTADO
-- CON LOS NOMBRES DE SUS JEFES
CREATE PROC SP_EMPLEADOJEFE(@EMPID INT, @PR VARCHAR(255) OUTPUT) AS
BEGIN
	DECLARE @INDICE INT

	SELECT @INDICE = ReportsTo FROM EMPLOYEES WHERE EMPLOYEEID=@EMPID
	SELECT @PR = FIRSTNAME FROM EMPLOYEES WHERE EMPLOYEEID=@INDICE

	WHILE @INDICE IS NOT NULL
	BEGIN
		SELECT @INDICE = ReportsTo FROM EMPLOYEES WHERE EMPLOYEEID=@INDICE
		IF @INDICE IS NOT NULL
			SELECT @PR = CONCAT(@PR, ', ',(SELECT FIRSTNAME FROM EMPLOYEES WHERE EMPLOYEEID=@INDICE))
	END

	SELECT @PR = ISNULL(@PR,'No tiene ningun jefe')

END

DECLARE @PR VARCHAR(255)
EXEC SP_EMPLEADOJEFE 9, @PR OUTPUT
SELECT @PR AS JEFES


