-- UN PROCEDIMIENTO ALMACENADO QUE REGRESE EL NOMBRE DEL CLIENTE Y TODAS LAS ORDENES QUE HIZO EL CLIENTE,
-- CODIGO Y DIAGRAMA DE FLUJO CON PROCESOS
CREATE PROC SP_ORDENESCLIENTE(@CUSTID NCHAR(5)) AS
BEGIN
	DECLARE @INDICE INT, @ORDENES VARCHAR(255)

	SELECT @INDICE = MIN(ORDERID) FROM ORDERS WHERE CUSTOMERID=@CUSTID
	SELECT @ORDENES=@INDICE

	WHILE @INDICE IS NOT NULL
	BEGIN
		SELECT @INDICE=MIN(ORDERID) FROM ORDERS WHERE CUSTOMERID=@CUSTID AND ORDERID>@INDICE
		IF @INDICE IS NOT NULL
			SELECT @ORDENES=CONCAT(@ORDENES,', ',@INDICE)
	END

	SELECT @CUSTID AS CLIENTE, ISNULL(@ORDENES,0) AS ORDENES
END

EXEC SP_ORDENESCLIENTE 'ANTON'