--1 CONSULTA CON EL FOLIO, FECHA DE LA ORDEN, NOMBRE DE LA COMPAÑÍA DE ENVIO, MOSTRAR LOS REGISTROS CUYO AÑO SEA MULTIPLO DE 3 Y EL MES CONTENGA LA LETRA R. 
SELECT o.OrderID, o.OrderDate, s.CompanyName, DATENAME(MONTH, o.OrderDate)
FROM Orders o
INNER JOIN Shippers s ON o.Shipvia = s.ShipperID
WHERE YEAR(o.OrderDate) % 3 = 0 AND DATENAME(MONTH, o.OrderDate) LIKE '%R%'

--2 CONSULTA CON EL FOLIO DE LA ORDEN, FECHA Y NOMBRE DEL CLIENTE QUE SE HAYAN REALIZADO LOS DIAS LUNES, MIÉRCOLES Y VIERNES Y QUE EL CLIENTE VIVA EN UN AVENIDA.
SELECT o.OrderID, o.OrderDate,c.ContactName,C.Address
FROM Orders o
INNER JOIN Customers c ON o.CustomerID=c.CustomerID
WHERE DATEPART(WEEKDAY,o.OrderDate)IN (2,4,6) AND C.Address LIKE '%Avda.%'

--3 CONSULTA CON LAS PRIMERAS 10 ORDENES DE 1997 DEL EMPLEADO QUE NACIERON EN LA DECADA DE 1960.
SELECT TOP 10 OrderID,OrderDate,e.BirthDate
FROM Orders o
INNER JOIN Employees e ON e.EmployeeID=o.EmployeeID
WHERE YEAR(o.OrderDate)=1997 AND YEAR(e.BirthDate) BETWEEN 1960 AND 1969

--4 CONSULTA CON EL NOMBRE DEL EMPLEADOS Y NOMBRE DE SU JEFE, MOSTRAR LOS EMPLEADOS QUE SU NOMBRE INICIE CON VOCAL Y TENGAN UNA REGION ASIGNADA. 
SELECT E.FirstName,e.LastName, j.FirstName,j.LastName, e.region 
FROM Employees e
INNER JOIN Employees j ON e.ReportsTo = j.EmployeeID
WHERE e.FirstName LIKE '[AEIOU]%' AND e.Region IS NOT NULL

--5 CONSULTA CON EL NOMBRE DEL PRODUCTO, NOMBRE DEL PROVEEDOR Y NOMBRE DE LA CATEGORIA. 
--  MOSTRAR SOLO LOS PROVEEDORES QUE SU TELEFONO INICIE CON 0,4 O 5 Y QUE NO TENGAN HOMEPAGE.
SELECT p.ProductName, s.ContactName, c.CategoryName, c.CategoryID
FROM Products p
INNER JOIN Suppliers s ON p.SupplierID = s.SupplierID
INNER JOIN Categories c ON p.CategoryID = c.CategoryID
WHERE S.PHONE LIKE '[045]%' AND s.HomePage IS NULL
GO

--6 CONSULTA CON EL NOMBRE DEL EMPLEADO Y NOMBRE DEL TERRITORIO QUE ATIENDE. 
--  MOSTRAR SOLO LOS NOMBRE DE EMPLEADO Y TERRITORIOS QUE EMPIECEN Y TERMINEN CON VOCAL.
SELECT e.FirstName, t.TerritoryDescription
FROM Employees e
INNER JOIN EmployeeTerritories et ON e.EmployeeID=et.EmployeeID
INNER JOIN Territories t ON t.TerritoryID=et.TerritoryID
WHERE e.FirstName LIKE '[aeiou]%[aeiou]' AND t.TerritoryDescription LIKE '[aeiou]%[aeiou]'

--7 CONSULTA CON EL FOLIO DE LA ORDEN, MESES TRANSCURRIDOS DE LA ORDEN, NOMBRE DEL EMPLEADO QUE HIZO LA ORDEN. 
--  MOSTRAR SOLO LAS ORDENES DE LOS EMPLEADOS QUE VIVAN EN EL PAIS “USA” Y QUE EL CODIGO POSTAL CONTENGA UN 2.    
SELECT o.OrderID, DATEDIFF(MONTH,o.OrderDate,GETDATE()), e.FirstName, e.Country,e.PostalCode
FROM Orders o
INNER JOIN Employees e ON o.EmployeeID=e.EmployeeID
WHERE e.Country LIKE 'USA' AND e.PostalCode LIKE '%2%'


--8 CONSULTA CON EL FOLIO DE LA ORDEN, NOMBRE DEL PRODUCTO E IMPORTE DE VENTA. MOSTRAR SOLO LAS ORDENES DE LOS PRODUCTOS 
--  CUYA CATEGERIA CONTENGA DOS VOCALES SEGUIDAS O QUE SU PENULTIMA LETRA SEA CONSONANTE.			
SELECT o.OrderID, p.ProductName, od.Quantity*od.UnitPrice,c.CategoryName
FROM Orders o
INNER JOIN [Order Details] od ON o.OrderID=od.OrderID
INNER JOIN Products p ON od.ProductID=p.ProductID
INNER JOIN Categories c ON c.CategoryID=p.CategoryID
WHERE c.CategoryName LIKE '%[aeiou][aeiou]%' OR c.CategoryName LIKE '%[^aeiou]_'

--9 CONSULTA CON EL NOMBRE DEL EMPLEADO, NOMBRE DEL TERRITORIO QUE ATIENDE. 
--  MOSTRAS SOLO LOS EMPLEADOS QUE EL TERRITORIO ESTE EN UNA REGION Y SU SEGUNDA LETRA SEA LA LETRA O.
SELECT e.FirstName, t.TerritoryDescription,r.RegionDescription,et.TerritoryID,t.RegionID
FROM Employees e
INNER JOIN EmployeeTerritories et ON e.EmployeeID=et.EmployeeID
INNER JOIN Territories t ON t.TerritoryID=et.TerritoryID
INNER JOIN Region r ON r.RegionID=t.RegionID
WHERE t.RegionID IS NOT NULL AND r.RegionDescription LIKE '_O%'

-- 10.- CONSULTA CON EL FOLIO DE LA ORDEN, FECHA DE LA ORDEN, NOMBRE DEL EMPLEADO, EDAD QUE TENIA EL EMPLEADO CUANDO HIZO LA ORDEN.
SELECT ORDERID,ORDERDATE,BIRTHDATE,FIRSTNAME, DATEDIFF(YEAR,BIRTHDATE,ORDERDATE) AS EDAD
FROM ORDERS O INNER JOIN EMPLOYEES E ON O.EmployeeID=E.EmployeeID


