--Vistas principales
CREATE VIEW VW_PRODUCTS AS
SELECT 
    P.PRODUCTID, P.PRODUCTNAME, P.QUANTITYPERUNIT, P.UNITPRICE, 
	P.UNITSINSTOCK, P.UNITSONORDER, P.REORDERLEVEL, P.DISCONTINUED, 

    C.CATEGORYID, C.CATEGORYNAME, C.DESCRIPTION, C.PICTURE,

    S.SUPPLIERID, S.COMPANYNAME, S.CONTACTNAME, S.CONTACTTITLE, S.ADDRESS, 
	S.CITY, S.REGION, S.POSTALCODE, S.COUNTRY, S.PHONE, S.FAX, S.HOMEPAGE
FROM PRODUCTS P
INNER JOIN CATEGORIES C ON P.CATEGORYID = C.CATEGORYID
INNER JOIN SUPPLIERS S ON P.SUPPLIERID = S.SUPPLIERID

GO

CREATE VIEW VW_ORDERS AS
SELECT 
	O.ORDERID,O.ORDERDATE,O.REQUIREDDATE,
	O.SHIPPEDDATE,O.FREIGHT,O.SHIPNAME,O.SHIPADDRESS,O.SHIPCITY,
	O.SHIPREGION,O.SHIPPOSTALCODE,O.SHIPCOUNTRY,

	C.CUSTOMERID,nomcliente=C.COMPANYNAME,C.CONTACTNAME,C.CONTACTTITLE,
	C.ADDRESS,C.CITY,custregion=C.REGION,custpostalcode=C.POSTALCODE,
	custcountry=C.COUNTRY,C.PHONE,C.FAX,

	E.EMPLOYEEID,E.LASTNAME,E.FIRSTNAME,E.TITLE,
	E.TITLEOFCOURTESY,E.BIRTHDATE,E.HIREDATE,empdir=E.ADDRESS,
	empcity=E.CITY,E.REGION,E.POSTALCODE,E.COUNTRY,E.HOMEPHONE,
	E.EXTENSION,E.PHOTO,E.NOTES,E.REPORTSTO,E.PHOTOPATH,

	S.SHIPPERID,NOMCOMENVIO=S.COMPANYNAME,shipphone=S.PHONE
FROM ORDERS O
INNER JOIN EMPLOYEES E ON O.EMPLOYEEID=E.EMPLOYEEID
INNER JOIN SHIPPERS S ON O.SHIPVIA=S.SHIPPERID
INNER JOIN CUSTOMERS C ON O.CUSTOMERID=C.CUSTOMERID

GO

CREATE VIEW VW_ORDERDETAILS AS
SELECT 
	OD.UNITPRICE, OD.QUANTITY, OD.DISCOUNT,

	O.ORDERID,O.ORDERDATE,O.REQUIREDDATE,
	O.SHIPPEDDATE,O.FREIGHT,O.SHIPNAME,O.SHIPADDRESS,O.SHIPCITY,
	O.SHIPREGION,O.SHIPPOSTALCODE,O.SHIPCOUNTRY,

	O.CUSTOMERID,O.nomcliente,ORDCONTACTNAME=O.CONTACTNAME,
	ORDCONTACTITLE=O.CONTACTTITLE, O.ADDRESS, O.CITY,
	O.custregion, O.custpostalcode, O.custcountry, O.PHONE, O.FAX,

	O.EMPLOYEEID,O.LASTNAME,O.FIRSTNAME,O.TITLE,
	O.TITLEOFCOURTESY,O.BIRTHDATE,O.HIREDATE,O.empdir,
	O.empcity,O.REGION,O.POSTALCODE,O.COUNTRY,O.HOMEPHONE,
	O.EXTENSION,O.PHOTO,O.NOTES,O.REPORTSTO,O.PHOTOPATH,

	O.SHIPPERID,O.NOMCOMENVIO,O.SHIPPHONE,

	P.PRODUCTID, P.PRODUCTNAME, P.QUANTITYPERUNIT, produnitprice=P.UNITPRICE, 
	P.UNITSINSTOCK, P.UNITSONORDER, P.REORDERLEVEL, P.DISCONTINUED, 

    P.CATEGORYID, P.CATEGORYNAME, P.DESCRIPTION,  P.PICTURE,

    P.SUPPLIERID, P.COMPANYNAME, P.CONTACTNAME, P.CONTACTTITLE, PRODADDRESS=P.ADDRESS, 
	PRODCITY=P.CITY, PRODREGION=P.REGION, PRODPOSTALCODE=P.POSTALCODE, PRODCOUNTRY=P.COUNTRY, 
	PRODPHONE=P.PHONE, PRODFAX=P.FAX, P.HOMEPAGE
FROM VW_ORDERS O
INNER JOIN [ORDER DETAILS] OD ON O.ORDERID=OD.ORDERID
INNER JOIN VW_PRODUCTS P ON P.PRODUCTID=OD.PRODUCTID
GO
--Vistas suplementarias
CREATE VIEW VW_TERRITORIES AS
SELECT 
	T.TERRITORYID,T.TERRITORYDESCRIPTION,
	R.REGIONID,R.REGIONDESCRIPTION
FROM TERRITORIES T
INNER JOIN REGION R ON T.REGIONID=R.REGIONID
GO
CREATE VIEW VM_EMPLOYEETERRITORIES AS
SELECT 
	T.TERRITORYID,T.TERRITORYDESCRIPTION,T.REGIONID,T.REGIONDESCRIPTION,

	E.EMPLOYEEID,E.LASTNAME,E.FIRSTNAME,E.TITLE,
	E.TITLEOFCOURTESY,E.BIRTHDATE,E.HIREDATE,E.ADDRESS,
	E.CITY,E.REGION,E.POSTALCODE,E.COUNTRY,E.HOMEPHONE,
	E.EXTENSION,E.PHOTO,E.NOTES,E.REPORTSTO,E.PHOTOPATH
FROM VW_TERRITORIES T
INNER JOIN EMPLOYEETERRITORIES ET ON ET.TERRITORYID=T.TERRITORYID
INNER JOIN EMPLOYEES E ON E.EMPLOYEEID=ET.EMPLOYEEID


