TITLE PROGRAM LEER UN CARACTER
.MODEL SMALL   
.STACK 100H
.DATA
    MSG1 DB 10,13,'DAME UN CARACTER: $'
    MSG2 DB 10,13,'LA MINUSCULA ES: $ '
    MSG3 DB 10,13,'LA MAYUSCULA ES: $'
    MSG4 DB 10,13,'CARACTER INVALIDO, VUELVE A INTENTAR: $'
    MSG5 DB 10,13,'QUIERES CONTINUAR(S/N): $'
    CHAR DB 0
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX
    
INICIO: 
    ;DESPLIEGA EL MENSAJE AL USUARIO
    LEA DX, MSG1
    MOV AH, 9
    INT 21H
    
    ;LEER CHAR
    MOV AH, 1
    INT 21H
    
    ;COMPARAR CHAR
    CMP AL,'a'
    JL MAYUSCULA
    CMP AL,'z'
    JG INVALIDO
    
MINUSCULA:
    ;SI LLEGA AQUI ES MINUSCULA, CONVERTIR A MAYUSCULA
    SUB AL, 32
    ;GUARDA CHAR    
    MOV CHAR, AL
    ;MENSAJE A DESPLEGAR ES EL DE MAYUSCULA
    LEA DX, MSG3
    JMP DESPLIEGA
MAYUSCULA:
    ;VALIDAR SI ES MAYUSCULA
    CMP AL,'A'
    JL INVALIDO
    CMP AL,'Z'
    JG INVALIDO
    ;SI LLEGA AQUI ES MAYUSCULA, CONVIERTE A MINUSCULA
    ADD AL,32
    ;GUARDAR EL CHAT
    MOV CHAR, AL
    ;MENSAJE A DESPLEGAR ES EL MINUSCULA
    LEA DX, MSG2
DESPLIEGA:
    MOV AH, 9
    INT 21H
    MOV DL, CHAR
    MOV AH, 2
    INT 21H
    JMP CONTINUA
CONTINUA:
    ;DESPLEGAR MENSAJE DE OPCION
    LEA DX, MSG5
    MOV AH, 9
    INT 21H
    ;GUARDARLO
    MOV AH, 1
    INT 21H
    ;COMPARAR LA DECISION
    CMP AL, 's'
    JE INICIO
    JNE FIN
    CMP AL, 'S'
    JE INICIO
    JNE FIN
    CMP AL, 'y'
    JE INICIO
    JNE FIN
    CMP AL, 'Y'
    JE INICIO
    JNE FIN
INVALIDO:
    LEA DX, MSG4
    MOV AH, 9
    INT 21H
    JMP INICIO   
    
    INT 21H
    JMP FIN
FIN:
    MOV AH, 4CH
    INT 21H
MAIN ENDP
    END MAIN