TITLE LEE DOS NUMEROS EN BINARIO, LOS SUMA Y DESPLIEGA RESULTADO
.MODEL SMALL
.STACK 100H
.DATA
    NUM1    DB 0
    NUM2    DB 0
    SUMABIN DB 0
    MSG1     DB 'DAME UN NUMERO BINARIO DE 8 BITS:$'
    MSG2    DB 10,13,'DAME OTRO NUMERO BINARIO DE 8 BITS:$'
    MSG3    DB 10,13,'LA SUMA ES:$'
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS, AX
    
    ;LEE PRIMER NUMERO BINARIO DE 8 BITS
    LEA DX, MSG1
    MOV AH,9
    INT 21H
    
    ;INICIALIZAR BH, PARA ALMACENAR EL NUMERO TEMPORALMENTE
    XOR BH,BH
    MOV CX, 8
    CICLO:
    ;HACER ESPACIO EN BH PARA EL PROXIMO BIT
    SHL BH, 1
    ;LEER CARACTER
    MOV AH, 1
    INT 21H
    ; CONVERTIR EL ASCII A NUMERO
    AND AL, 0FH
    ; METERLO A BH 
    OR BH, AL
    LOOP CICLO
    MOV NUM1, BH
    
    ;LEER SEGUNDO NUMERO BINARIO DE 8 BITS 
    LEA DX, MSG2
    MOV AH, 9
    INT 21H
    ;INICIALIZAR BH, PARA ALMACENAR EL NUMERO TEMPORALMENTE
    XOR BH,BH
    MOV CX, 8
     CICLO2:
    ;HACER ESPACIO EN BH PARA EL PROXIMO BIT
    SHL BH, 1
    ;LEER CARACTER
    MOV AH, 1
    INT 21H
    ; CONVERTIR EL ASCII A NUMERO
    AND AL, 0FH
    ; METERLO A BH 
    OR BH, AL
    LOOP CICLO2
    MOV NUM2, BH
    
    ;REALIZAR SUMA
    MOV BH, NUM1
    ADD BH, NUM2
    MOV SUMABIN, BH
    
    ;DESPLEGAR LA SUMA
    LEA DX,MSG3
    MOV AH,9
    INT 21H
    
    ; DESPLEGAR LA SUMA
    MOV CX, 8
CICLO_DISP:
    XOR DL, DL
    ROL SUMABIN, 1
    RCL DL, 1
    OR DL, 30H
    MOV AH, 2
    INT 21H
    LOOP CICLO_DISP
    
    MOV AH, 4CH
    INT 21H
MAIN ENDP
    END MAIN