TITLE PROGRAM LEA UN HEXADECIMAL DE HASTA 4 CIFRAS
.MODEL SMALL
.STACK 100H
.DATA

    MSG1 DB 10,13,'DAME UN NUMERO: $'
    MSG2 DB 10,13,'ES INVALIDO DAME OTRO$'
    NUM1 DW 0
    
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DX, AX
    
INICIO:
    ;DESPLIEGA SOLICITUD
    MOV AH, 9
    LEA DX, MSG1
    INT 21H
    
    MOV CX, 4
    
    ;GUARDA EL NUMERO
CICLO:
    MOV AH, 1
    INT 21H
    CMP AL, '0'
    JL INVALIDO
    CMP AL, '9'
    JLE TRANSFORMAR_NUM
    CMP AL, '9'
    JG MAYUSCULA
MAYUSCULA:
    CMP AL, 'A'
    JL INVALIDO
    CMP AL, 'F'
    JLE TRANSFORMAR_MAY
    CMP AL, 'F'
    JG MINUSCULA
       
MINUSCULA:
    CMP AL, 'a'
    JL INVALIDO
    CMP AL, 'f'
    JG INVALIDO
    CMP AL, 'f'
    JLE TRANSFORMAR_MIN
;TRANSFORMAR LA LETRA A NUMERO
TRANSFORMAR_NUM:
    AND AL, 0FH
    JMP GUARDA
;TRANSFORMAR LA LETRA MAY A NUMERO
TRANSFORMAR_MAY:
    SUB AL, 55
    JMP GUARDA
;TRANSFORMAR LA LETRA MIN A NUMERO
TRANSFORMAR_MIN:
    SUB AL, 87
    JMP GUARDA
GUARDA:
    PUSH CX
    MOV CL, 4
    SHL NUM1, CL
    POP CX
    CBW
    OR NUM1, AX
    LOOP CICLO
    JMP FIN
   
INVALIDO:
    LEA DX, MSG2 
    MOV AH,9
    INT 21H
    JMP INICIO
    
FIN:
    MOV AH, 4CH
    INT 21H
MAIN ENDP
    END MAIN