TITLE LEE DOS NUMEROS EN BINARIO, LOS SUMA Y DESPLIEGA RESULTADO
.MODEL SMALL
.STACK 100H
.DATA
    NUM1 DB 0
    NUM2 DB 0
    SUMABIN DB 0
    RESTABIN DB 0
    MULTBIN DW 0
    MULTSIGNOBIN DW 0
    
    MSG1 DB 'DAME UN NUMERO BINARIO DE 8 BITS: $'
    MSG2 DB 10,13,'DAME OTRO NUMERO BINARIO DE 8 BITS: $'
    MSG3 DB 10,13,'LA SUMA ES: $'
    MSG4 DB 10,13,'LA RESTA ES: $'
    MSG5 DB 10,13,'LA MULTIPLICACION SIN SIGNO ES: $'
    MSG6 DB 10,13,'LA MULTIPLICACION CONSIGNO ES: $'
 
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX
    
    ;LEER PRIMER NUMERO
    LEA DX, MSG1
    MOV AH, 9
    INT 21H
    
    ;INICIALIZO BH EN CERO
    XOR BH, BH
    MOV CX, 8
    
CICLO:
    ;HACER ESPACIO EN BH
    SHL BH,1
    ;LEER CHAR
    MOV AH, 1 
    INT 21H
    ;CONVERTIR DE CHAR A NUMERO
    AND AL, 0FH
    ;METER A BG
    OR BH,AL
    LOOP CICLO
    MOV NUM1, BH
  
   ;LEER PRIMER NUMERO2
   LEA DX, MSG2
    MOV AH, 9
    INT 21H
    
    ;INICIALIZO BH EN CERO
    XOR BH, BH
    MOV CX, 8
    
CICLO2:
    ;HACER ESPACIO EN BH
    SHL BH,1
    ;LEER CHAR
    MOV AH, 1 
    INT 21H
    ;CONVERTIR DE CHAR A NUMERO
    AND AL, 0FH
    ;METER A BG
    OR BH,AL
    LOOP CICLO2
    MOV NUM2, BH
    
    ;desplegar lo que hay en num1
    MOV CX, 8
    
    ;REALIZAR LA SUMA
    MOV BH, NUM1
    ADD BH, NUM2
    MOV SUMABIN, BH
    
    ;DESPLEGAR LA SUMA
    LEA DX, MSG3
    MOV AH, 9
    INT 21H
    MOV CX, 8
    
    CICLO_DISP2:
    ;INICIALIZO DL EN 0
    XOR DL, DL
    ;SACO 1 BIT DE NUM1 Y LO METO A DL
    ROL SUMABIN, 1
    RCL DL, 1
    ;CONVIERTO DE NUM A CHAR
    OR DL, 30H
    

    MOV AH, 2
    INT 21H
    LOOP CICLO_DISP2
    
    ;REALIZAR LA RESTA 
    MOV BH, NUM1
    SUB BH, NUM2
    MOV RESTABIN, BH

    ;DESPLEGAR LA RESTA
    LEA DX, MSG4
    MOV AH, 9
    INT 21H
    MOV CX, 8
    
    CICLO_DISP3:
    ;INICIALIZO DL EN 0
    XOR DL, DL
    ;SACO 1 BIT DE NUM1 Y LO METO A DL
    ROL RESTABIN, 1
    RCL DL, 1
    ;CONVIERTO DE NUM A CHAR
    OR DL, 30H
    
    MOV AH, 2
    INT 21H
    LOOP CICLO_DISP3 
   
    ;REALIZAR LA MULTIPLICACION 
    MOV AL, NUM1
    MOV BL, NUM2
    MUL BL
    MOV MULTBIN, AX

    ;DESPLEGAR LA MULTIPLICACION
    LEA DX, MSG5
    MOV AH, 9
    INT 21H
    MOV CX, 16
    
    CICLO_DISP4:
    ;INICIALIZO DL EN 0
    XOR DL, DL
    ;SACO 1 BIT DE NUM1 Y LO METO A DL
    ROL MULTBIN, 1
    RCL DL, 1
    ;CONVIERTO DE NUM A CHAR
    OR DL, 30H
    
    MOV AH, 2
    INT 21H
    LOOP CICLO_DISP4 
    
    ;REALIZAR LA MULTIPLICACION CON SIGNO
    MOV AL, NUM1
    MOV BL, NUM2
    IMUL BL
    MOV MULTSIGNOBIN, AX

    ;DESPLEGAR LA MULTIPLICACION CON SIGNO
    LEA DX, MSG6
    MOV AH, 9
    INT 21H
    MOV CX, 16
    
    CICLO_DISP5:
    ;INICIALIZO DL EN 0
    XOR DL, DL
    ;SACO 1 BIT DE NUM1 Y LO METO A DL
    ROL MULTSIGNOBIN, 1
    RCL DL, 1
    ;CONVIERTO DE NUM A CHAR
    OR DL, 30H
    
    MOV AH, 2
    INT 21H
    LOOP CICLO_DISP5 
    
    MOV AH, 4CH
    INT 21H
MAIN ENDP
    END MAIN