 TITLE LEE DOS NUMEROS EN BINARIO, LOS SUMA Y DESPLIEGA RESULTADO
.MODEL SMALL
.STACK 100H
.DATA
    NUM1 DB 0
    NUM2 DB 0
    SUMABIN DB 0
    RESTABIN DB 0
    MULTBIN DW 0
    MULTSIGNOBIN DW 0
    
    MSG1 DB 'DAME UN NUMERO DECIMAL: $'
    MSG2 DB 10,13,'DAME OTRO NUMERO DECIMAL: $'
    MSG3 DB 10,13,'LA SUMA ES: $'
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX
    
    ;LEER PRIMER NUMERO
    LEA DX, MSG1
    MOV AH, 9
    INT 21H
    
    ;INICIALIZO BH EN CERO
    XOR BX, BX
    MOV CX, 5
    
CICLO:
    ;HACER ESPACIO EN BH
    SHL BX,1
    ;LEER CHAR
    MOV AX, 1 
    INT 21H
    ;CONVERTIR DE CHAR A NUMERO
    SUB AX, 48
    MUL BX, 10
    ADD BX, AH
    ;METER A BX
    
    LOOP CICLO
    MOV NUM1, BX
  
   ;LEER  NUMERO2
    LEA DX, MSG2
    MOV AH, 9
    INT 21H
    
    ;INICIALIZO BH EN CERO
    XOR BX, BX
    MOV CX, 5
    
CICLO2:
    ;HACER ESPACIO EN BH
    SHL BX,1
    ;LEER CHAR
    MOV AX, 1 
    INT 21H
    ;CONVERTIR DE CHAR A NUMERO
    SUB AX, 48
    MUL BX, 10
    ADD BX, AX
    ;METER A BX
    
    LOOP CICLO2
    MOV NUM2, BH
    
    ;desplegar lo que hay en num1
    MOV CX, 5
    
    ;REALIZAR LA SUMA
    MOV BX, NUM1
    ADD BX, NUM2
    MOV SUMABIN, BX
    
    ;DESPLEGAR LA SUMA
    LEA DX, MSG3
    MOV AH, 9
    INT 21H
    MOV CX, 5
    
    CICLO_DISP2:
    ;INICIALIZO DL EN 0
    XOR DL, DL
    ;SACO 1 BIT DE NUM1 Y LO METO A DL
    ROL SUMABIN, 1
    RCL DL, 1
    ;CONVIERTO DE NUM A CHAR
    OR DL, 30H
    

    MOV AH, 2
    INT 21H
    LOOP CICLO_DISP2
    

    
    MOV AH, 4CH
    INT 21H
MAIN ENDP
    END MAIN