CREATE DATABASE FERRETERIA
GO
USE FERRETERIA
GO
CREATE TABLE  ZONAS (
    ZONAID INT NOT NULL,
    ZONANOMBRE NVARCHAR (50) NOT NULL,
    ZONADESCRIPCION NVARCHAR (200) NULL,
)
GO
CREATE TABLE MUNICIPIOS (
    MUNID INT NOT NULL,
    MUNNOMBRE NVARCHAR (50) NOT NULL
)
GO
CREATE TABLE COLONIAS (
    COLID INT NOT NULL,
    COLNOMBRE NVARCHAR (50) NOT NULL,
    COLCP NCHAR (5) NULL,
    MUNID INT NOT NULL
)
GO
CREATE TABLE FAMILIAS (
    FAMID INT NOT NULL,
    FAMNOMBRE NVARCHAR (50) NOT NULL,
    FAMDESCRIPCION NVARCHAR (200) NULL
)
GO
CREATE TABLE FERRETERIAS (
    FERRID INT NOT NULL,
    FERRNOMBRE NVARCHAR (20) NOT NULL,
    FERRDOMICILIO NVARCHAR (50) NOT NULL,
    FERRTELEFONO NCHAR (10) NOT NULL
)
GO
CREATE TABLE EMPLEADOS (
    EMPID INT NOT NULL,
    EMPNOMBRE NVARCHAR (50) NOT NULL,
    EMPAPEPAT NVARCHAR (50) NOT NULL,
    EMPAPEMAT NVARCHAR (50) NULL,
    EMPDOMICILIO NVARCHAR (50) NOT NULL,
    EMPTELEFONO NCHAR (10) NULL,
    EMPCELULAR NCHAR (10) NULL,
    EMPRFC NCHAR (18) NULL,
    EMPCURP NCHAR (13) NULL,
    EMPFECHAINGRESO DATETIME NOT NULL,
    EMPFECHANACIMIENTO DATETIME NOT NULL,
    ZONAID INT NOT NULL,
    JEFEID INT NULL
)
GO
CREATE TABLE CLIENTES (
    CTEID INT NOT NULL,
    CTENOMBRE NVARCHAR (50) NOT NULL,
    CTEAPEPAT NVARCHAR (50) NOT NULL,
    CTEAPEMAT NVARCHAR (50) NULL,
    CTEDOMICILIO NVARCHAR (50) NOT NULL,
    CTETELEFONO NCHAR (10) NULL,
    CTECELULAR NCHAR (10) NULL,
    CTERFC NCHAR (18) NULL,
    CTECURP NCHAR (13) NULL,
    CTEFECHANACIMIENTO DATETIME NOT NULL,
    CTESEXO NCHAR (1) NOT NULL,
    COLID INT NOT NULL
)
GO
CREATE TABLE ARTICULOS (
    ARTID INT NOT NULL,
    ARTNOMBRE NVARCHAR (20) NOT NULL,
    ARTDESCRIPCION NVARCHAR (200) NOT NULL,
    ARTPRECIO NUMERIC (10, 2) NOT NULL,
    FAMID INT NOT NULL
)
GO
CREATE TABLE VENTAS (
    FOLIO INT NOT NULL,
    FECHA DATETIME NOT NULL,
    FERRID INT NOT NULL,
    CTEID INT NOT NULL,
    EMPID INT NOT NULL 
)
GO
CREATE TABLE DETALLE (
    FOLIO INT NOT NULL,
    ARTID INT NOT NULL,
    CANTIDAD NUMERIC (7, 2) NOT NULL,
    PRECIO NUMERIC (10, 2) NOT NULL
)
GO
--LLAVES PRIMARIAS
ALTER TABLE DETALLE ADD CONSTRAINT PK_DETALLE PRIMARY KEY (FOLIO, ARTID)
GO
ALTER TABLE MUNICIPIOS ADD CONSTRAINT PK_MUNICIPIOS PRIMARY KEY (MUNID)
GO
ALTER TABLE COLONIAS ADD CONSTRAINT PK_COLONIAS PRIMARY KEY (COLID)
GO
ALTER TABLE EMPLEADOS ADD CONSTRAINT PK_EMPLEADOS PRIMARY KEY (EMPID)
GO
ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (CTEID)
GO
ALTER TABLE ARTICULOS ADD CONSTRAINT PK_ARTICULOS PRIMARY KEY (ARTID)
GO
ALTER TABLE FAMILIAS ADD CONSTRAINT PK_FAMILIAS PRIMARY KEY (FAMID)
GO
ALTER TABLE VENTAS ADD CONSTRAINT PK_VENTAS PRIMARY KEY (FOLIO)
GO
ALTER TABLE FERRETERIAS ADD CONSTRAINT PK_FERRETERIAS PRIMARY KEY (FERRID)
GO
ALTER TABLE ZONAS ADD CONSTRAINT PK_ZONAS PRIMARY KEY (ZONAID)
GO
--Llaves foraneas
ALTER TABLE EMPLEADOS ADD CONSTRAINT FK_EMP_EMP FOREIGN KEY(JEFEID) REFERENCES EMPLEADOS(EMPID)
ALTER TABLE EMPLEADOS ADD CONSTRAINT FK_EMP_ZONAS FOREIGN KEY(ZONAID)REFERENCES ZONAS(ZONAID)
ALTER TABLE ARTICULOS ADD CONSTRAINT FK_ARTICULOS_FAMILIAS FOREIGN KEY(FAMID)REFERENCES FAMILIAS(FAMID)
ALTER TABLE COLONIAS ADD CONSTRAINT FK_COLONIAS_MUN FOREIGN KEY (MUNID)REFERENCES MUNICIPIOS(MUNID)
ALTER TABLE CLIENTES ADD CONSTRAINT FK_CLIENTES_COL FOREIGN KEY (COLID)REFERENCES COLONIAS (COLID)
ALTER TABLE VENTAS ADD CONSTRAINT FK_VENTAS_FERR FOREIGN KEY (FERRID)REFERENCES FERRETERIAS(FERRID)
ALTER TABLE VENTAS ADD CONSTRAINT FK_VENTAS_CTE FOREIGN KEY (CTEID)REFERENCES CLIENTES(CTEID)
ALTER TABLE VENTAS ADD CONSTRAINT FK_VENTAS_EMP FOREIGN KEY(EMPID)REFERENCES EMPLEADOS(EMPID)
ALTER TABLE DETALLE ADD CONSTRAINT FK_DETALLE_FOL FOREIGN KEY(FOLIO)REFERENCES VENTAS(FOLIO)
ALTER TABLE DETALLE ADD CONSTRAINT FK_DETALLE_ART FOREIGN KEY(ARTID)REFERENCES ARTICULOS(ARTID)
GO
--LLAVES UNICAS
ALTER TABLE EMPLEADOS ADD CONSTRAINT UN_RFC_EMP UNIQUE(EMPRFC)
ALTER TABLE EMPLEADOS ADD CONSTRAINT UN_CURP_EMP UNIQUE(EMPCURP)
ALTER TABLE CLIENTES ADD CONSTRAINT UN_RFC_CTE UNIQUE(CTERFC)
ALTER TABLE CLIENTES ADD CONSTRAINT UN_CURP_CTE UNIQUE(CTECURP)
--RESTRICCIONES DE COMPROBACION
ALTER TABLE CLIENTES ADD 
CONSTRAINT CC_CTE_SEXO CHECK(CTESEXO IN ('H','M')),
CONSTRAINT CC_CTE_RFC_CURP CHECK(CTERFC<>CTECURP)
GO
ALTER TABLE EMPLEADOS ADD 
CONSTRAINT CC_EMP_RFC_CURP CHECK(EMPRFC<>EMPCURP)
GO
ALTER TABLE DETALLE ADD
CONSTRAINT CC_DET_PRECIO CHECK(PRECIO>0),
CONSTRAINT CC_DET_CANTIDAD CHECK(CANTIDAD>0)
GO
ALTER TABLE ARTICULOS ADD 
CONSTRAINT CC_ART_PRECIO CHECK(ARTPRECIO>0)
GO
--VALOR PREDEFINIDO
ALTER TABLE EMPLEADOS ADD
CONSTRAINT DC_EMP_DOM DEFAULT('DOMICILIO DESCONOCIDO')FOR EMPDOMICILIO,
CONSTRAINT DC_EMP_TEL DEFAULT('SIN TELEFONO')FOR EMPTELEFONO
GO
ALTER TABLE CLIENTES ADD 
CONSTRAINT DC_CLIENTES_DOM DEFAULT('DOMICILIO DESCONOCIDO')FOR CTEDOMICILIO,
CONSTRAINT DC_CLIENTES_TEL DEFAULT('SIN TELEFONO')FOR CTETELEFONO
GO
ALTER TABLE COLONIAS ADD
CONSTRAINT DC_COL_CP DEFAULT('00000')FOR COLCP
GO
--INSERCIONES
INSERT ZONAS VALUES (1, 'NORTE', 'ZONA NORTE')
INSERT ZONAS VALUES (2, 'SUR', 'ZONA SUR')
INSERT ZONAS VALUES (3, 'ESTE', 'ZONA ESTE')
INSERT ZONAS VALUES (4, 'OESTE', 'ZONA OESTE')
INSERT ZONAS VALUES (5, 'SURESTE', 'ZONA SURESTE')
GO
INSERT MUNICIPIOS VALUES(1,'Culiacan')
INSERT MUNICIPIOS VALUES(2,'Mazatlan')
INSERT MUNICIPIOS VALUES(3,'Ahome')
INSERT MUNICIPIOS VALUES(4,'Guasave')
INSERT MUNICIPIOS VALUES(5,'Los Mochis')
GO
INSERT COLONIAS VALUES(1,'El Acueducto',DEFAULT,1)
INSERT COLONIAS VALUES(2,'San Pedro','95032',2)
INSERT COLONIAS VALUES(3,'El santo','72042',3)
INSERT COLONIAS VALUES(4,'Parroquial','63031',4)
INSERT COLONIAS VALUES(5,'Cisnero','34263',5)
GO
INSERT FERRETERIAS VALUES(1,'La Fierrona','Acueducto de Tembleque 4890','6676060647')
INSERT FERRETERIAS VALUES(2,'El Fierron','Huizaches 5421','6677070647')
INSERT FERRETERIAS VALUES(3,'Los Fierros','Barrancos 9845','6678080647')
INSERT FERRETERIAS VALUES(4,'Los Herreros','Lomita 9874','6672020647')
INSERT FERRETERIAS VALUES(5,'Herramientas Pro','Alvaro Obregon 3216','6675050647')
GO
INSERT FAMILIAS VALUES (1,'HERRAMIENTAS','ARTICULOS PARA FACILITAR EL DIA A DIA')
INSERT FAMILIAS VALUES (2,'ELECTRICA','ARTICULOS DE ELECTRICIDAD')
INSERT FAMILIAS VALUES (3,'MATERIALES','ARTICULOS DE CONSTRUCCION')
INSERT FAMILIAS VALUES (4,'NEUMATICA','ARTICULOS PARA VEHICULOS')
INSERT FAMILIAS VALUES (5,'PLOMERIA','ARTICULOS PARA LAVADOS�Y�BA�OS')
GO
INSERT ARTICULOS VALUES(1,'Martillo','El mejor martillo',50.50,1)
INSERT ARTICULOS VALUES(2,'Bombilla','Luz led',70.99,2)
INSERT ARTICULOS VALUES(3,'Tabique','Tabique para construccion',40.50,3)
INSERT ARTICULOS VALUES(4,'Llanta','Llanta michelin grande',60.50,4)
INSERT ARTICULOS VALUES(5,'Cinta','Cinta metrica para medir',30.50,5)
GO
INSERT CLIENTES VALUES(1,'Juan Miguel','Garcia','Picos','Dunas 5725','6677107813','6677092023','GAPJ030208HSLRCNA6','GAPJ030208GH3','2-13-2003','H',1)
INSERT CLIENTES VALUES(2,'KARINA','PINKY','FELIX','Pavellon 9512','6676217813','6676092023','PIFK020617MSLNLRA3','PIFK020617D29','6-17-2002','M',2)
INSERT CLIENTES VALUES(3,'Dylan Michel','Garcia','Figueroa','Amorada 4852','6677107813','6679092023','GAFD040720HSLRGYA4','GAFD040720HQ2','7-20-2004','H',3)
INSERT CLIENTES VALUES(4,'Carmen','Sanchez','Sanchez','Lobo 1562','6677107813','6671092023','SASC030129MSLNNRA7','SASC030129BN9','1-29-2003','M',4)
INSERT CLIENTES VALUES(5,'Xochitl','Inzunza','Perez','Infonavit 6234','6657107813','6672092023','IIPX030802HSLNRCA1','IUPX0308027A0','8-2-2003','M',5)
GO
INSERT EMPLEADOS VALUES (1,'JUAN','PONCE','LOPEZ','ALVARADO 5894','6675489825','6678452154','POLJ940603HSLNPN02','POLJ940603IP5','10-11-2021','3-6-1994',1,NULL)
INSERT EMPLEADOS VALUES (2,'MARIA','LOPEZ','CAZARES','OBREGON 478','6675567850','6673489408','LOCM980423MSLPZR01','LOC980423A610','6-12-2016','4-23-1998',2,2)
INSERT EMPLEADOS VALUES (3,'DYLAN','GARCIA','RODRIGUEZ','�HUMAYA 3450','6677874846','6675486924','GARD030504HSLRDYA7','GARD030504BGA','2-5-2018','4-5-2003',3,3)
INSERT EMPLEADOS VALUES (4,'PABLO','PONCE','LOPEZ','�DUNAS 7895','6673456478','6672070749','POLP001019HSLNPBA1','POLP001019QT2','11-25-2017','10-19-2000',4,4)
INSERT EMPLEADOS VALUES (5,'DANIEL','SALCEDO','SMITH','�PRIMAVERA 340','6676890015','6678967821','SASD990504MSLLMN08','SABD990504GN4','10-29-2016','4-5-1999',5,5)
GO
INSERT VENTAS VALUES (1,'3-28-2023',5,1,1)
INSERT VENTAS VALUES (2,'5-15-2023',4,2,2)
INSERT VENTAS VALUES (3,'7-13-2023',3,3,3)
INSERT VENTAS VALUES (4,'10-26-2023',2,4,4)
INSERT VENTAS VALUES (5,'8-11-2023',1,5,5)
GO
INSERT DETALLE VALUES(1,1,5,100.50)
INSERT DETALLE VALUES(2,2,10,80.00)
INSERT DETALLE VALUES(3,3,15,70.50)
INSERT DETALLE VALUES(4,4,20,60.50)
INSERT DETALLE VALUES(5,5,25,90.50)

